[General]
bEnabled=1

[Dialogue]
bAllowMovement=1
bAllowRunning=0
bAllowJumping=0
bAllowSneaking=0
bAllowPOVSwitch=0
bDebugLog=0

[AutoClose]
bAutoClose=1
; Metres
fAutoCloseDistance=19
fAutoCloseTolerance=6

[Camera]
bEdgeRotation=1
; Share of the screen (0-0.5)
fEdgeSize=0.12
fEdgeSpeed=12
